import {v} from "convex/values";
import {validateTrip} from "@passenger/core";
import {mutation} from "./_generated/server";
import type {MutationCtx} from "./_generated/server";
import type {Doc} from "./_generated/dataModel";
import {audit,fail,getTierLimits,note,notifyParticipants,releaseCapacity,requireUser,requireVerified} from "./lib";
import {assertSupportedRoute,getServiceArea} from "./serviceArea";
import {refundForShipment} from "./wallet";
export const tripArgs={origin:v.string(),destination:v.string(),stops:v.array(v.string()),departureAt:v.number(),arrivalAt:v.number(),capacityKg:v.number(),acceptedCategories:v.optional(v.array(v.string())),maxParcelWeightKg:v.optional(v.number()),handlingNotes:v.optional(v.string())};
export const createDefinition={args:tripArgs,handler:async(ctx:MutationCtx,args:any)=>{const u=await requireUser(ctx);requireVerified(u);await assertSupportedRoute(ctx,args.origin,args.destination);validateTrip(args);const limits=await getTierLimits(ctx,u);if(args.capacityKg>limits.maxCapacityKg)fail(`Your ${limits.tier} allows carrying at most ${limits.maxCapacityKg} kg per trip. Request a tier upgrade after verification.`);const id=await ctx.db.insert("trips",{...args,origin:args.origin.trim(),destination:args.destination.trim(),stops:args.stops.map((s:string)=>s.trim()),acceptedCategories:args.acceptedCategories??[],handlingNotes:args.handlingNotes?.trim(),travellerId:u._id,reservedKg:0,status:"active"});await audit(ctx,u,"trip.created",`Trip published: ${id}.`);return id;}};
export const create=mutation(createDefinition);
export const update=mutation({args:{tripId:v.id("trips"),...tripArgs},handler:async(ctx,{tripId,...args})=>{const u=await requireUser(ctx);requireVerified(u);const t=await ctx.db.get(tripId);if(!t||t.travellerId!==u._id)fail("Your trip was not found.");if(t.status==="cancelled"||t.status==="completed"||t.departureAt<=Date.now())fail("Only active future trips may be edited.");const bookings=await ctx.db.query("shipments").withIndex("by_trip",q=>q.eq("tripId",tripId)).collect();if(bookings.some(s=>s.reservationActive||!["cancelled","open","rejected"].includes(s.status)))fail("Route and carrying preferences cannot change after booking commitments.");await assertSupportedRoute(ctx,args.origin,args.destination);validateTrip(args);const limits=await getTierLimits(ctx,u);if(args.capacityKg>limits.maxCapacityKg)fail(`Your ${limits.tier} allows carrying at most ${limits.maxCapacityKg} kg per trip. Request a tier upgrade after verification.`);const offers=await ctx.db.query("offers").withIndex("by_trip",q=>q.eq("tripId",tripId)).collect();for(const o of offers)if(o.status==="pending")await ctx.db.patch(o._id,{status:"withdrawn"});await ctx.db.patch(tripId,{...args,origin:args.origin.trim(),destination:args.destination.trim(),stops:args.stops.map(s=>s.trim()),acceptedCategories:args.acceptedCategories??[],handlingNotes:args.handlingNotes?.trim()});await audit(ctx,u,"trip.updated","Trip edited; previous pending offers withdrawn.");}});
export async function cancelBooking(ctx:MutationCtx,s:Doc<"shipments">,reason:string,actor:Doc<"users">|null){if(["cancelled","delivered"].includes(s.status))return;if(s.status==="disputed")fail("Resolve the linked open dispute before cancelling this trip.");if(s.status==="in_transit")fail("A parcel is already in transit; open a dispute for support.");if(["released","refunded","refund_pending","payout_pending","payout_failed"].includes(s.paymentStatus))fail("A finance operation requires review before cancellation.");const funded=["held","reconciliation_required"].includes(s.paymentStatus);if(s.paymentStatus==="held"){const sender=await ctx.db.get(s.senderId);if(sender)await refundForShipment(ctx,sender,s._id,s.feeNaira,`Trip cancelled: ${reason}`);}await ctx.db.patch(s._id,{status:"cancelled",paymentStatus:s.paymentStatus==="held"?"refunded":s.paymentStatus,cancellationReason:reason,refundApproved:funded,updatedAt:Date.now()});await releaseCapacity(ctx,s);await notifyParticipants(ctx,s,"Booking cancelled",funded?"Delivery fee refunded to sender's wallet.":"Booking cancelled. Any late payment will be quarantined for refund reconciliation.");await audit(ctx,actor,"shipment.cancelled",reason,s._id);}
export const cancel=mutation({args:{tripId:v.id("trips"),reason:v.string()},handler:async(ctx,args)=>{const u=await requireUser(ctx);const t=await ctx.db.get(args.tripId);if(!t||t.travellerId!==u._id)fail("Your trip was not found.");if(t.status==="cancelled")return;const reason=note(args.reason,"Cancellation reason",5);const bookings=await ctx.db.query("shipments").withIndex("by_trip",q=>q.eq("tripId",t._id)).collect();for(const s of bookings)await cancelBooking(ctx,s,`Traveller cancelled trip: ${reason}`,u);const offers=await ctx.db.query("offers").withIndex("by_trip",q=>q.eq("tripId",t._id)).collect();for(const o of offers)if(o.status==="pending")await ctx.db.patch(o._id,{status:"withdrawn"});await ctx.db.patch(t._id,{status:"cancelled",cancellationReason:reason,reservedKg:0});await audit(ctx,u,"trip.cancelled",reason);}});
