import {v} from "convex/values";
import {routeSegment} from "@passenger/core";
import {mutation,query} from "./_generated/server";
import type {MutationCtx} from "./_generated/server";
import type {Doc,Id} from "./_generated/dataModel";
import {audit,fail,getTierLimits,isAdmin,legLoads,note,notify,notifyParticipants,offerDto,requireSender,requireUser,requireVerified,shipment} from "./lib";

export async function compatible(ctx:MutationCtx,s:Doc<"shipments">,t:Doc<"trips">){const now=Date.now();if(s.status!=="open"||!s.approved||!["held","unpaid","failed"].includes(s.paymentStatus))fail("Only approved open parcels accept offers.");if(t.status==="cancelled"||t.status==="completed"||t.departureAt<=now)fail("Choose an active future trip.");const segment=routeSegment(s,t);if(!segment)fail("Pickup must precede drop-off along the ordered trip route.");if(!s.readyAt||!s.deliveryDeadline||!t.arrivalAt)fail("Update legacy parcel/trip timing before matching.");const windowStart=s.preferredPickupAt===undefined?s.readyAt:s.preferredPickupAt-(s.pickupFlexBeforeMinutes??0)*60000;const windowEnd=s.preferredPickupAt===undefined?undefined:s.preferredPickupAt+(s.pickupFlexAfterMinutes??0)*60000;if(t.departureAt<windowStart||(windowEnd!==undefined&&t.departureAt>windowEnd)||t.arrivalAt>s.deliveryDeadline)fail("Trip timing does not fit the parcel pickup window and delivery deadline.");const accepted=t.acceptedCategories?.length?t.acceptedCategories:undefined;if(accepted&&!accepted.includes(s.category))fail("This traveller does not accept the parcel category.");if(s.weightKg>(t.maxParcelWeightKg??t.capacityKg))fail("Parcel exceeds this traveller's per-parcel weight limit.");if(!s.safetyConsent||!s.evidenceIds?.length)fail("Parcel requires current safety declaration and evidence.");if(s.weightKg<=0||s.weightKg>25||s.valueNaira<=0||s.valueNaira>500000)fail("Parcel exceeds supported weight or value.");const sender=await ctx.db.get(s.senderId);if(sender){const limits=await getTierLimits(ctx,sender);if(s.valueNaira>limits.maxShipmentValueNaira)fail(`The sender's ${limits.tier} permits declaring parcel value up to ₦${limits.maxShipmentValueNaira.toLocaleString()}.`);}const loads=await legLoads(ctx,t);for(let i=segment.pickupIndex;i<segment.dropoffIndex;i++)if(loads[i]!+s.weightKg>t.capacityKg+0.000001)fail("Insufficient capacity on an overlapping trip leg.");return{segment,loads};}

export async function proposeOffer(ctx:MutationCtx,args:{shipmentId:Id<"shipments">;tripId:Id<"trips">;expiresAt:number;note:string}) {const u=await requireUser(ctx);requireVerified(u);const s=await shipment(ctx,args.shipmentId);const t=await ctx.db.get(args.tripId);if(!t||t.travellerId!==u._id)fail("Only the trip owner can propose an offer.");if(s.senderId===u._id)fail("You cannot carry your own shipment.");const sender=await ctx.db.get(s.senderId);if(!sender)fail("Sender unavailable.");requireVerified(sender);await compatible(ctx,s,t);if(!Number.isFinite(args.expiresAt)||args.expiresAt<=Date.now()||args.expiresAt>Math.min(t.departureAt,Date.now()+48*3600000))fail("Offer expiry must be before departure and within 48 hours.");const old=await ctx.db.query("offers").withIndex("by_shipment",q=>q.eq("shipmentId",s._id)).collect();if(old.some(o=>o.tripId===t._id&&o.status==="pending"&&o.expiresAt>Date.now()))fail("Withdraw the existing offer before proposing another.");const detail=note(args.note,"Offer note",0,500);const id=await ctx.db.insert("offers",{...args,feeNaira:s.feeNaira,note:detail,travellerId:u._id,createdAt:Date.now(),status:"pending"});await notify(ctx,s.senderId,"New traveller offer","Review the trip details before accepting.",s._id);await audit(ctx,u,"offer.proposed","Traveller proposed; no capacity reserved.",s._id);return id;}

export const propose=mutation({args:{shipmentId:v.id("shipments"),tripId:v.id("trips"),expiresAt:v.number(),note:v.string()},handler:proposeOffer});

export const accept=mutation({args:{offerId:v.id("offers")},handler:async(ctx,args)=>{const u=await requireUser(ctx);requireVerified(u);const o=await ctx.db.get(args.offerId);if(!o||o.status!=="pending"||o.expiresAt<=Date.now())fail("This offer is no longer available.");const s=await shipment(ctx,o.shipmentId);requireSender(s,u);const t=await ctx.db.get(o.tripId);if(!t||t.travellerId!==o.travellerId||t.travellerId===u._id)fail("Invalid traveller trip.");const traveller=await ctx.db.get(t.travellerId);if(!traveller)fail("Traveller unavailable.");requireVerified(traveller);const {segment,loads}=await compatible(ctx,s,t);const unresolved=await ctx.db.query("payments").withIndex("by_shipment",q=>q.eq("shipmentId",s._id)).collect();if(unresolved.some(p=>p.status!=="failed"&&p.status!=="paid"))fail("An existing payment reference needs reconciliation before a new booking.");if(s.paymentStatus==="held")await ctx.db.patch(s._id,{status:"funded",paymentStatus:"held",travellerId:t.travellerId,tripId:t._id,feeNaira:o.feeNaira,reservationActive:true,...segment,acceptedOfferId:o._id,updatedAt:Date.now()});else{const payByAt=Math.min(Date.now()+30*60000,t.departureAt);if(payByAt-Date.now()<5*60000)fail("At least five minutes are required before departure to accept.");await ctx.db.patch(s._id,{status:"matched",paymentStatus:"unpaid",travellerId:t.travellerId,tripId:t._id,feeNaira:o.feeNaira,reservationActive:true,...segment,acceptedOfferId:o._id,payByAt,updatedAt:Date.now()});}for(let i=segment.pickupIndex;i<segment.dropoffIndex;i++)loads[i]!+=s.weightKg;await ctx.db.patch(t._id,{reservedKg:Math.max(0,...loads)});const all=await ctx.db.query("offers").withIndex("by_shipment",q=>q.eq("shipmentId",s._id)).collect();for(const offer of all)if(offer.status==="pending")await ctx.db.patch(offer._id,{status:offer._id===o._id?"accepted":"declined"});await notifyParticipants(ctx,s,s.paymentStatus==="held"?"Parcel matched and funded":"Parcel matched","Check the delivery record for next steps.");await audit(ctx,u,"offer.accepted",`Sender accepted traveller offer at ₦${o.feeNaira.toLocaleString()}.`,s._id);}});

export const decline=mutation({args:{offerId:v.id("offers")},handler:async(ctx,args)=>{const u=await requireUser(ctx);const o=await ctx.db.get(args.offerId);if(!o||o.status!=="pending")fail("Pending offer not found.");requireSender(await shipment(ctx,o.shipmentId),u);await ctx.db.patch(o._id,{status:"declined"});await notify(ctx,o.travellerId,"Offer declined","The sender declined your offer.",o.shipmentId);}});
export const withdraw=mutation({args:{offerId:v.id("offers")},handler:async(ctx,args)=>{const u=await requireUser(ctx);const o=await ctx.db.get(args.offerId);if(!o||o.travellerId!==u._id||o.status!=="pending")fail("Your pending offer was not found.");await ctx.db.patch(o._id,{status:"withdrawn"});}});
export const list=query({args:{shipmentId:v.optional(v.id("shipments"))},handler:async(ctx,args)=>{const u=await requireUser(ctx);const rows=args.shipmentId?await ctx.db.query("offers").withIndex("by_shipment",q=>q.eq("shipmentId",args.shipmentId!)).collect():await ctx.db.query("offers").collect();const result=[];for(const o of rows){const s=await ctx.db.get(o.shipmentId);if(isAdmin(u)||o.travellerId===u._id||s?.senderId===u._id)result.push(await offerDto(ctx,o));}return result.sort((a,b)=>b.createdAt-a.createdAt);}});
